### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by abramsm** [cmcdonaldca/CakePHP-Shopify-Plugin#6]
Hello.  Thanks for creating this plugin.  We wanted to use this in our tools but there is currently no license file.  Looks like https://github.com/notmaintained/shopify.php/blob/master/LICENSE.txt is using a MIT license.  Would be willing to add a version to this project?

Thanks for your help,
Matt

**Comment by cmcdonaldca** [comment]
I don't see a PR in my repo, but I added it here: 

https://github.com/cmcdonaldca/CakePHP-Shopify-Plugin/blob/master/LICENSE

Good luck with your project!

**Comment by abramsm** [comment]
Thanks!!
